server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: employee-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_management
    username: emp_admin
    password: emp_password123
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql
    
  sql:
    init:
      mode: never

# Logging
logging:
  level:
    com.company.employee: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always