server:
  port: 8082
  servlet:
    context-path: /

spring:
  application:
    name: department-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_management
    username: emp_admin
    password: emp_password123
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql

logging:
  level:
    com.company.department: DEBUG
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics